_core:
  default_config_hash: ijfbzDTN4CbE7Sr-6ubWzy_t1vH4OtU1doNCLssVz-4
langcode: pt-br
uuid: e1b67eaa-c09d-47bb-a534-3bc4dc7fd4b5
name: 'Seu guia'
mail: fe7rodrigues@gmail.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: pt-br
mail_notification: null
